# Generated by Django 5.2.10 on 2026-01-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Lady', 'Lady'), ('Ind.', 'Ind.'), ('Pr.', 'Pr.'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Mx.', 'Mx.'), ('Mrs.', 'Mrs.'), ('Sir', 'Sir'), ('Mr.', 'Mr.')], max_length=60),
        ),
    ]
