# Generated by Django 5.2.10 on 2026-01-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Mx.', 'Mx.'), ('Pr.', 'Pr.'), ('Ms.', 'Ms.'), ('Ind.', 'Ind.'), ('Mrs.', 'Mrs.')], max_length=60),
        ),
    ]
