# Generated by Django 5.2.10 on 2026-01-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Pr.', 'Pr.'), ('Sir', 'Sir'), ('Mr.', 'Mr.'), ('Lady', 'Lady'), ('Ind.', 'Ind.'), ('Mrs.', 'Mrs.'), ('Mx.', 'Mx.'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.')], max_length=60),
        ),
    ]
