# Generated by Django 5.2.10 on 2026-01-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Pr.', 'Pr.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Mrs.', 'Mrs.'), ('Mx.', 'Mx.'), ('Dr.', 'Dr.'), ('Ind.', 'Ind.')], max_length=60),
        ),
    ]
