# Generated by Django 5.2.10 on 2026-01-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Lady', 'Lady'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Ind.', 'Ind.'), ('Sir', 'Sir'), ('Pr.', 'Pr.'), ('Mx.', 'Mx.')], max_length=60),
        ),
    ]
