# Generated by Django 5.2.10 on 2026-01-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Lady', 'Lady'), ('Pr.', 'Pr.'), ('Ind.', 'Ind.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Sir', 'Sir'), ('Mx.', 'Mx.'), ('Mrs.', 'Mrs.')], max_length=60),
        ),
    ]
